### ISSUE TITLE
在raspberry中运行报错，在电脑虚拟机中正常

### ISSUE THREAD

**Issue by luozhaohua1** [xiaoshan5733/tmallbot#1]
请问一下，为什么我在raspberry中运行npm start时报 错     跪请赐教，谢谢
> node app

module.js:472
    throw err;
    ^

Error: Cannot find module './lib'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/tmallbot-master/lib/auth-server/index.js:0)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

npm ERR! Linux 4.9.35-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tmallbot@0.0.0 start: `node app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tmallbot@0.0.0 start script 'node app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tmallbot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app
npm ERR! You can get information on how to open an issue for this project wit
npm ERR!     npm bugs tmallbot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tmallbot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/.npm/_logs/2018-08-05T06_42_09_916Z-debug.log

**Comment by wengqianshan** [comment]
@luozhaohua1 再重新拉下代码，重新 npm install 试下，想必是auth-server的问题，我把auth-server改成模块安装了，如果还不行，尝试把node 更新到最新版吧 🤣

**Comment by luozhaohua1** [comment]
问题解决了，是因为express没有安装好

**Comment by wengqianshan** [comment]
好的，我把问题关了
