### ISSUE TITLE
适用于天猫精灵方糖吗？

### ISSUE THREAD

**Issue by 1206403782** [xiaoshan5733/tmallbot#2]
运行的时候在天猫网页那提示返回的token错误。不知道什么原因

**Comment by 1206403782** [comment]
正在获取Token……
Oauth token 返回不正确,请检查, 3秒后返回设备列表
然后 会显示插座设备页面

**Comment by wengqianshan** [comment]
@1206403782 你好，请问配置都正确吗，这个项目我好久没维护了，不确定 token 生成方式有没有变，我来看下

**Comment by 1206403782** [comment]
@xiaoshan5733 感谢，主要是对OAuth2一直搞不懂怎么对接，所以 打算参考一下。

**Comment by wengqianshan** [comment]
![image](https://user-images.githubusercontent.com/854370/58857080-ea16d900-86d6-11e9-806c-4441f5633924.png)
@1206403782 我试了这边也不行，然后去翻了官方文档发现需要开启 https 协议，不知道是不是这个原因导致的，我这边暂时不太方便启用https，要不你先试下 https，不好意思啊

**Comment by 1206403782** [comment]
@xiaoshan5733 好的，现在很多家都是启用https，我想办法加下https。

**Comment by 1206403782** [comment]
@xiaoshan5733 你好，我根据这个教程里做了https，修改app.js和开放平台的服务设置。运行后还是那个样子，是OAuth2的原因？您有空可以帮助我看看是什么原因吗？ 麻烦你啦
https://www.jb51.net/article/140590.htm

**Comment by wengqianshan** [comment]
@1206403782 你好，原因找到了，官方文档中回调字段expires_in的单位是秒，而我在项目中用的auth-server模块生成的是日期字符串，导致校验不通过，临时解决方法为修改
./node_modules/auth-server/lib/authServer.js  31行内容如下

```
this.getExpiresDate = function () {
        return expiresIn * 1000;
        // return new Date(new Date().getTime() + expiresIn * 60000);
    };
```

![image](https://user-images.githubusercontent.com/854370/58878071-ffa2f780-8704-11e9-8c35-bcaadc55e98a.png)

**Comment by 1206403782** [comment]
@xiaoshan5733 感谢，我有空先试一下

**Comment by wengqianshan** [comment]
@1206403782 可以用最新的代码，已经修复了这个问题

**Comment by 1206403782** [comment]
Nice已经可以啦，谢谢，接下来可以继续研究对接我们的网关的API了。
